-- 자료 AI 요약. 목적은 화면 표시가 아니라 투두 추천(S-16-B)의 프롬프트 비용 절감이다 —
-- 추천은 아카이브 전체를 프롬프트에 넣으므로 본문 대신 요약을 넣으면 자료 20건 기준
-- 약 117,000 tok → 약 2,600 tok 이 된다(ai/docs/EXPERIMENTS.md #8 실측 기반).
--
-- nullable 이다. 요약이 없는 것이 정상인 경우가 셋 있다:
--   ① 이 마이그레이션 이전에 등록된 자료 — 백필하지 않는다.
--   ② crawl_status = 'PENDING' — 요약할 본문이 아직 없다.
--   ③ 요약 LLM 호출 실패 — AI 태깅 실패와 같은 폴백으로 등록 자체는 막지 않는다.
-- 추천은 요약이 없으면 본문을 쓴다(요약·본문 중 짧은 쪽, specs/OPEN.md 2026-07-30 확정).
--
-- VARCHAR(500)인 이유: 프롬프트가 "2~3문장 · 200자 이내"를 요구하고, 모델이 그걸 넘겼을 때
-- 잘라 담을 여유를 둔다(ArchiveTextLimits.MAX_SUMMARY 와 같은 값이어야 한다).
ALTER TABLE archive_items ADD COLUMN summary VARCHAR(500);
